#!/bin/bash

echo '----Script Begins----'

wcthreshold=$1
echo $wc_threshold

for h in {1..18}
do

for i in {0..10}
do
python3.3 TweetStatistics.py --eventno $i --minframe $(($h*60)) --dayback 8 --wcount $wcthreshold > out$((h*60))m8d${wcthreshold}w${i}e &
done

wait

done
wait

echo 'Second Part Begins'
# ---- second part ----

for h in {1..18}
do

for i in {11..20}
do
python3.3 TweetStatistics.py --eventno $i --minframe $(($h*60)) --dayback 8 --wcount $wcthreshold > out$((h*60))m8d${wcthreshold}w${i}e &
done

wait

done
wait

echo '3. Part Begins'
# ---- second part ----

for h in {1..18}
do

for i in {21..30}
do
python3.3 TweetStatistics.py --eventno $i --minframe $(($h*60)) --dayback 8 --wcount $wcthreshold > out$((h*60))m8d${wcthreshold}w${i}e &
done

wait

done
wait

echo 'Third and Last part Starts'
